"""Initial migration

Revision ID: 7db89e7c9ad9
Revises: 2c448fd8ed34
Create Date: 2023-08-22 12:02:05.455979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db89e7c9ad9'
down_revision = '2c448fd8ed34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_status')
    # ### end Alembic commands ###
